version: "2"
services:
 kafka:
  image: wurstmeister/kafka
  ports:
   - "39092:39092"
  depends_on:
   - zookeeper
  environment:
   - KAFKA_ZOOKEEPER_CONNECT=zookeeper
   - KAFKA_LISTENERS=INTERNAL://:39092
   - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:39092
   - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
   - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:SSL,INTERNAL:PLAINTEXT
  volumes:
   - ./volumes/kafka/:/var/lib/kafka/data
  networks:
   - apps_devenv
 zookeeper:
  image: 'bitnami/zookeeper:latest'
  ports:
   - '2181:2181'
  environment:
   - ALLOW_ANONYMOUS_LOGIN=yes
  volumes:
   - ./volumes/zookeeper/:/bitnami/zookeeper
   - ./volumes/zk-data:/var/lib/zookeeper/data
   - ./volumes/zk-data:/bitnami/zookeeper
   - ./volumes/zk-txn-logs:/var/lib/zookeeper/log
  networks:
   - apps_devenv
 producer_counter:
  build: .
  depends_on:
   - kafka
  environment:
   - BOOTSTRAP_SERVERS=kafka:39092
   - ACKS=all
   - RETRIES=3
   - MAX_NUM=100
   - TOPIC=Counter
  networks:
   - apps_devenv  

networks:
 apps_devenv:
  driver: bridge
